/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.primeraaplicaciongrafica;

import static com.mycompany.primeraaplicaciongrafica.Opcion.INSERCION;
import static com.mycompany.primeraaplicaciongrafica.Opcion.MODIFICACION;
import java.awt.Component;
import java.io.File;
import static java.lang.Integer.parseInt;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import javax.swing.JTextField;


enum Opcion {INSERCION,MODIFICACION,BORRADO}

/**
 *
 * @author matomas
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        DesactivarCampos(panelFormularioDepartamento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaPestanyas = new javax.swing.JTabbedPane();
        panelPestanyaDepartamento = new javax.swing.JPanel();
        panelGlobalDepartamento = new javax.swing.JPanel();
        panelFormularioDepartamento = new javax.swing.JPanel();
        etiquetaIDDepartamento = new javax.swing.JLabel();
        etiquetaNombreDepartamento = new javax.swing.JLabel();
        etiquetaLocalidadDepartamento = new javax.swing.JLabel();
        campoIDDepartamento = new javax.swing.JTextField();
        campoNombreDepartamento = new javax.swing.JTextField();
        campoLocalidadDepartamento = new javax.swing.JTextField();
        panelAccionesDepartamento = new javax.swing.JPanel();
        botonInsertarDepartamento = new javax.swing.JButton();
        botonActualizarDepartamento = new javax.swing.JButton();
        botonBorrarDepartamento = new javax.swing.JButton();
        panelMoverseDepartamento = new javax.swing.JPanel();
        botonPrincipioDepartamento = new javax.swing.JButton();
        botonAnteriorDepartamento = new javax.swing.JButton();
        botonSiguienteDepartamento = new javax.swing.JButton();
        botonUltimoDepartamento = new javax.swing.JButton();
        panelAceptarCancelarDepartamento = new javax.swing.JPanel();
        botonAceptarDepartamento = new javax.swing.JButton();
        botonCancelarDepartamento = new javax.swing.JButton();
        pestanyaScripts = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        botonCargarScriptEjecutarScript = new javax.swing.JButton();
        botonEjecutarEjecutarScript = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPestanyaDepartamento.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelPestanyaDepartamentoComponentShown(evt);
            }
        });

        panelGlobalDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Departamentos"));

        etiquetaIDDepartamento.setText("Identificador");

        etiquetaNombreDepartamento.setText("Nombre");

        etiquetaLocalidadDepartamento.setText("Localidad");

        campoIDDepartamento.setEnabled(false);

        campoNombreDepartamento.setEnabled(false);

        campoLocalidadDepartamento.setEnabled(false);

        javax.swing.GroupLayout panelFormularioDepartamentoLayout = new javax.swing.GroupLayout(panelFormularioDepartamento);
        panelFormularioDepartamento.setLayout(panelFormularioDepartamentoLayout);
        panelFormularioDepartamentoLayout.setHorizontalGroup(
            panelFormularioDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
            .addGroup(panelFormularioDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFormularioDepartamentoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelFormularioDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etiquetaLocalidadDepartamento)
                        .addComponent(campoLocalidadDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoIDDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiquetaIDDepartamento)
                        .addComponent(etiquetaNombreDepartamento)
                        .addComponent(campoNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelFormularioDepartamentoLayout.setVerticalGroup(
            panelFormularioDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelFormularioDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFormularioDepartamentoLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(etiquetaIDDepartamento)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(campoIDDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(etiquetaNombreDepartamento)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(campoNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(etiquetaLocalidadDepartamento)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(campoLocalidadDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        botonInsertarDepartamento.setText("Insertar");
        botonInsertarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarDepartamentoActionPerformed(evt);
            }
        });

        botonActualizarDepartamento.setText("Actualizar");
        botonActualizarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarDepartamentoActionPerformed(evt);
            }
        });

        botonBorrarDepartamento.setText("Borrar");

        javax.swing.GroupLayout panelAccionesDepartamentoLayout = new javax.swing.GroupLayout(panelAccionesDepartamento);
        panelAccionesDepartamento.setLayout(panelAccionesDepartamentoLayout);
        panelAccionesDepartamentoLayout.setHorizontalGroup(
            panelAccionesDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAccionesDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonInsertarDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(botonBorrarDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelAccionesDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAccionesDepartamentoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(botonActualizarDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelAccionesDepartamentoLayout.setVerticalGroup(
            panelAccionesDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesDepartamentoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonInsertarDepartamento)
                .addGap(58, 58, 58)
                .addComponent(botonBorrarDepartamento)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(panelAccionesDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAccionesDepartamentoLayout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(botonActualizarDepartamento)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        botonPrincipioDepartamento.setText("|<");

        botonAnteriorDepartamento.setText("<");

        botonSiguienteDepartamento.setText("<");

        botonUltimoDepartamento.setText(">|");

        javax.swing.GroupLayout panelMoverseDepartamentoLayout = new javax.swing.GroupLayout(panelMoverseDepartamento);
        panelMoverseDepartamento.setLayout(panelMoverseDepartamentoLayout);
        panelMoverseDepartamentoLayout.setHorizontalGroup(
            panelMoverseDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMoverseDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonPrincipioDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAnteriorDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSiguienteDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonUltimoDepartamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMoverseDepartamentoLayout.setVerticalGroup(
            panelMoverseDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMoverseDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botonPrincipioDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAnteriorDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSiguienteDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonUltimoDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonAceptarDepartamento.setText("Aceptar");
        botonAceptarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarDepartamentoActionPerformed(evt);
            }
        });

        botonCancelarDepartamento.setText("Cancelar");

        javax.swing.GroupLayout panelAceptarCancelarDepartamentoLayout = new javax.swing.GroupLayout(panelAceptarCancelarDepartamento);
        panelAceptarCancelarDepartamento.setLayout(panelAceptarCancelarDepartamentoLayout);
        panelAceptarCancelarDepartamentoLayout.setHorizontalGroup(
            panelAceptarCancelarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAceptarCancelarDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAceptarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCancelarDepartamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAceptarCancelarDepartamentoLayout.setVerticalGroup(
            panelAceptarCancelarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAceptarCancelarDepartamentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAceptarCancelarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptarDepartamento)
                    .addComponent(botonCancelarDepartamento))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelGlobalDepartamentoLayout = new javax.swing.GroupLayout(panelGlobalDepartamento);
        panelGlobalDepartamento.setLayout(panelGlobalDepartamentoLayout);
        panelGlobalDepartamentoLayout.setHorizontalGroup(
            panelGlobalDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlobalDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlobalDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlobalDepartamentoLayout.createSequentialGroup()
                        .addComponent(panelFormularioDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelAccionesDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(panelGlobalDepartamentoLayout.createSequentialGroup()
                        .addComponent(panelMoverseDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAceptarCancelarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelGlobalDepartamentoLayout.setVerticalGroup(
            panelGlobalDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlobalDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlobalDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelAccionesDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFormularioDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGlobalDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMoverseDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAceptarCancelarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout panelPestanyaDepartamentoLayout = new javax.swing.GroupLayout(panelPestanyaDepartamento);
        panelPestanyaDepartamento.setLayout(panelPestanyaDepartamentoLayout);
        panelPestanyaDepartamentoLayout.setHorizontalGroup(
            panelPestanyaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPestanyaDepartamentoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panelGlobalDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPestanyaDepartamentoLayout.setVerticalGroup(
            panelPestanyaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPestanyaDepartamentoLayout.createSequentialGroup()
                .addComponent(panelGlobalDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        ventanaPestanyas.addTab("Departamentos", panelPestanyaDepartamento);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        botonCargarScriptEjecutarScript.setText("Cargar Script");
        botonCargarScriptEjecutarScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarScriptEjecutarScriptActionPerformed(evt);
            }
        });

        botonEjecutarEjecutarScript.setText("Ejecutar Script");
        botonEjecutarEjecutarScript.setEnabled(false);

        javax.swing.GroupLayout pestanyaScriptsLayout = new javax.swing.GroupLayout(pestanyaScripts);
        pestanyaScripts.setLayout(pestanyaScriptsLayout);
        pestanyaScriptsLayout.setHorizontalGroup(
            pestanyaScriptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestanyaScriptsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pestanyaScriptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pestanyaScriptsLayout.createSequentialGroup()
                        .addGap(0, 342, Short.MAX_VALUE)
                        .addComponent(botonCargarScriptEjecutarScript)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEjecutarEjecutarScript)))
                .addContainerGap())
        );
        pestanyaScriptsLayout.setVerticalGroup(
            pestanyaScriptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestanyaScriptsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pestanyaScriptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCargarScriptEjecutarScript)
                    .addComponent(botonEjecutarEjecutarScript))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        ventanaPestanyas.addTab("Ejecutar Script", pestanyaScripts);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        ventanaPestanyas.addTab("tab3", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ventanaPestanyas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ventanaPestanyas)
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInsertarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarDepartamentoActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
        ActivarCampos();
        
        op= INSERCION;   
        
    }//GEN-LAST:event_botonInsertarDepartamentoActionPerformed

    private void panelPestanyaDepartamentoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelPestanyaDepartamentoComponentShown
        // TODO add your handling code here:
        LimpiarCampos();
    }//GEN-LAST:event_panelPestanyaDepartamentoComponentShown

    private void botonAceptarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarDepartamentoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_botonAceptarDepartamentoActionPerformed

    private void botonActualizarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarDepartamentoActionPerformed
        // TODO add your handling code here:
        campoLocalidadDepartamento.setEnabled(true);
        campoNombreDepartamento.setEnabled(true);
        
        op=MODIFICACION;
    }//GEN-LAST:event_botonActualizarDepartamentoActionPerformed

    private void botonCargarScriptEjecutarScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarScriptEjecutarScriptActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonCargarScriptEjecutarScriptActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new vista().setVisible(true);
//            }
//        });
//    }

    
    
    private void ActivarCampos(){
        campoIDDepartamento.setEnabled(true);
        campoNombreDepartamento.setEnabled(true);
        campoLocalidadDepartamento.setEnabled(true);
    }
    
    private void LimpiarCampos(){
        campoIDDepartamento.setText("");
        campoNombreDepartamento.setText("");
        campoLocalidadDepartamento.setText("");
    }
    
    private void DesactivarCampos(JPanel panel){
        for(var campo: panel.getComponents()){
            if(campo.getClass()==JTextField.class){
                campo.setEnabled(false);
            }
        }
    }
    
    public void MostrarMensajeError(String mensajeError){
        showMessageDialog(this, "Error: "+mensajeError);
        
    }
    
    public Departamento recuperarDatosDepartamento(){
        return new Departamento(parseInt(campoIDDepartamento.getText()),campoNombreDepartamento.getText() ,campoLocalidadDepartamento.getText());
    }

    public JButton getBotonAceptarDepartamento() {
        return botonAceptarDepartamento;
    }

    public void setBotonAceptarDepartamento(JButton botonAceptarDepartamento) {
        this.botonAceptarDepartamento = botonAceptarDepartamento;
    }

    public JButton getBotonCargarScriptEjecutarScript() {
        return botonCargarScriptEjecutarScript;
    }

    public void setBotonCargarScriptEjecutarScript(JButton botonCargarScriptEjecutarScript) {
        this.botonCargarScriptEjecutarScript = botonCargarScriptEjecutarScript;
    }
    
    public File selecionarFichero(){
        var ficheroSeleccionado = new JFileChooser().getSelectedFile();
        return ficheroSeleccionado;
    }
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarDepartamento;
    private javax.swing.JButton botonActualizarDepartamento;
    private javax.swing.JButton botonAnteriorDepartamento;
    private javax.swing.JButton botonBorrarDepartamento;
    private javax.swing.JButton botonCancelarDepartamento;
    private javax.swing.JButton botonCargarScriptEjecutarScript;
    private javax.swing.JButton botonEjecutarEjecutarScript;
    private javax.swing.JButton botonInsertarDepartamento;
    private javax.swing.JButton botonPrincipioDepartamento;
    private javax.swing.JButton botonSiguienteDepartamento;
    private javax.swing.JButton botonUltimoDepartamento;
    private javax.swing.JTextField campoIDDepartamento;
    private javax.swing.JTextField campoLocalidadDepartamento;
    private javax.swing.JTextField campoNombreDepartamento;
    private javax.swing.JLabel etiquetaIDDepartamento;
    private javax.swing.JLabel etiquetaLocalidadDepartamento;
    private javax.swing.JLabel etiquetaNombreDepartamento;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelAccionesDepartamento;
    private javax.swing.JPanel panelAceptarCancelarDepartamento;
    private javax.swing.JPanel panelFormularioDepartamento;
    private javax.swing.JPanel panelGlobalDepartamento;
    private javax.swing.JPanel panelMoverseDepartamento;
    private javax.swing.JPanel panelPestanyaDepartamento;
    private javax.swing.JPanel pestanyaScripts;
    private javax.swing.JTabbedPane ventanaPestanyas;
    // End of variables declaration//GEN-END:variables

    private Opcion op = null;
    
    private File ficheroSeleccionado = null;

    public File getFicheroSeleccionado() {
        return ficheroSeleccionado;
    }

    public void setFicheroSeleccionado(File ficheroSeleccionado) {
        this.ficheroSeleccionado = ficheroSeleccionado;
    }

    public Opcion getOp() {
        return op;
    }

    public void setOp(Opcion op) {
        this.op = op;
    }
    
    

}
