/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.iespacomolla.ad.accesodatos;

import es.iespacomolla.ad.hibernateaccesodatos.Equipo;
import java.awt.Color;
import java.awt.Component;
import java.awt.Rectangle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.TabbedPaneUI;
import javax.swing.plaf.basic.BasicTabbedPaneUI;

/**
 *
 * @author miguel
 */
public class VentanaControlador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaControlador
     */
    public VentanaControlador() {
        initComponents();
       
        TabbedPaneUIModificado uiModificado = new TabbedPaneUIModificado();
              
        panelPestanyas.setUI(uiModificado);
        panelPestanyas.setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        botonEquipoLateral = new javax.swing.JButton();
        botonJugadoresLateral = new javax.swing.JButton();
        botonEntrenadoresLateral = new javax.swing.JButton();
        botonLesionesLateral = new javax.swing.JButton();
        etiquetaLogotipo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelSuperior = new javax.swing.JPanel();
        etiquetaRutaPanelSuperior = new javax.swing.JLabel();
        etiquetaTituloPanelSuperio = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelPestanyas = new javax.swing.JTabbedPane();
        panelEquipos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaConferenciaEquipos = new javax.swing.JList<>();
        comboSeleccionConferencia = new javax.swing.JComboBox<>();
        panelDetallesEquipo = new javax.swing.JPanel();
        etiquetaCiudadEquipo = new javax.swing.JLabel();
        campoCiudadEquipo = new javax.swing.JTextField();
        etiquetaDivisionEquipo = new javax.swing.JLabel();
        comboDivisionEquipo = new javax.swing.JComboBox<>();
        etiquetaConferenciaEquipo = new javax.swing.JLabel();
        comboConferenciaEquipo = new javax.swing.JComboBox<>();
        etiquetaModificarEquipo = new javax.swing.JLabel();
        botonModificarEquipo = new javax.swing.JButton();
        etiquetaNombreEquipo = new javax.swing.JLabel();
        campoNombreEquipo = new javax.swing.JTextField();
        panelJugadores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setAlignmentX(0.0F);
        panelFondo.setAlignmentY(0.0F);

        panelLateral.setBackground(new java.awt.Color(0, 67, 140));
        panelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonEquipoLateral.setBackground(new java.awt.Color(0, 67, 140));
        botonEquipoLateral.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        botonEquipoLateral.setForeground(new java.awt.Color(255, 255, 255));
        botonEquipoLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoEquipo.png"))); // NOI18N
        botonEquipoLateral.setText("Equipo");
        botonEquipoLateral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 26, 50)));
        botonEquipoLateral.setBorderPainted(false);
        botonEquipoLateral.setContentAreaFilled(false);
        botonEquipoLateral.setFocusPainted(false);
        botonEquipoLateral.setIconTextGap(20);
        botonEquipoLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEquipoLateralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEquipoLateralMouseExited(evt);
            }
        });
        botonEquipoLateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEquipoLateralActionPerformed(evt);
            }
        });
        panelLateral.add(botonEquipoLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 257, 55));

        botonJugadoresLateral.setBackground(new java.awt.Color(0, 67, 140));
        botonJugadoresLateral.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        botonJugadoresLateral.setForeground(new java.awt.Color(255, 255, 255));
        botonJugadoresLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoJugador.png"))); // NOI18N
        botonJugadoresLateral.setText("Jugadores");
        botonJugadoresLateral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 26, 50)));
        botonJugadoresLateral.setBorderPainted(false);
        botonJugadoresLateral.setContentAreaFilled(false);
        botonJugadoresLateral.setFocusPainted(false);
        botonJugadoresLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonJugadoresLateralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonJugadoresLateralMouseExited(evt);
            }
        });
        botonJugadoresLateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugadoresLateralActionPerformed(evt);
            }
        });
        panelLateral.add(botonJugadoresLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 201, 257, 55));

        botonEntrenadoresLateral.setBackground(new java.awt.Color(0, 67, 140));
        botonEntrenadoresLateral.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        botonEntrenadoresLateral.setForeground(new java.awt.Color(255, 255, 255));
        botonEntrenadoresLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoEntrenador.png"))); // NOI18N
        botonEntrenadoresLateral.setText("Entrenadores");
        botonEntrenadoresLateral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 26, 50)));
        botonEntrenadoresLateral.setBorderPainted(false);
        botonEntrenadoresLateral.setContentAreaFilled(false);
        botonEntrenadoresLateral.setFocusPainted(false);
        botonEntrenadoresLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEntrenadoresLateralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEntrenadoresLateralMouseExited(evt);
            }
        });
        botonEntrenadoresLateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrenadoresLateralActionPerformed(evt);
            }
        });
        panelLateral.add(botonEntrenadoresLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 262, 257, 55));

        botonLesionesLateral.setBackground(new java.awt.Color(0, 67, 140));
        botonLesionesLateral.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        botonLesionesLateral.setForeground(new java.awt.Color(255, 255, 255));
        botonLesionesLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoLesion.png"))); // NOI18N
        botonLesionesLateral.setText("Lesiones");
        botonLesionesLateral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 26, 50)));
        botonLesionesLateral.setBorderPainted(false);
        botonLesionesLateral.setContentAreaFilled(false);
        botonLesionesLateral.setFocusPainted(false);
        botonLesionesLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonLesionesLateralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonLesionesLateralMouseExited(evt);
            }
        });
        botonLesionesLateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLesionesLateralActionPerformed(evt);
            }
        });
        panelLateral.add(botonLesionesLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 323, 257, 55));

        etiquetaLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopequenyo.png"))); // NOI18N
        panelLateral.add(etiquetaLogotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 79));
        panelLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 240, -1));

        panelSuperior.setBackground(new java.awt.Color(218, 26, 50));

        etiquetaRutaPanelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaRutaPanelSuperior.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        etiquetaRutaPanelSuperior.setText("Management\\Equipos");

        etiquetaTituloPanelSuperio.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        etiquetaTituloPanelSuperio.setText("Equipos de la liga");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaRutaPanelSuperior)
                    .addComponent(etiquetaTituloPanelSuperio, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(etiquetaRutaPanelSuperior)
                .addGap(29, 29, 29)
                .addComponent(etiquetaTituloPanelSuperio)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panelPestanyas.setBackground(new java.awt.Color(255, 255, 255));
        panelPestanyas.setFocusable(false);

        panelEquipos.setBackground(new java.awt.Color(255, 255, 255));

        listaConferenciaEquipos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "equipo 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaConferenciaEquipos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaConferenciaEquipos.setSelectionBackground(new java.awt.Color(218, 26, 50));
        listaConferenciaEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaConferenciaEquiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaConferenciaEquipos);

        comboSeleccionConferencia.setBackground(new java.awt.Color(255, 255, 255));
        comboSeleccionConferencia.setMaximumRowCount(5);
        comboSeleccionConferencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Este", "Oeste" }));
        comboSeleccionConferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionConferenciaActionPerformed(evt);
            }
        });

        panelDetallesEquipo.setBackground(new java.awt.Color(255, 255, 255));
        panelDetallesEquipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Equipo"));

        etiquetaCiudadEquipo.setText("Ciudad");

        campoCiudadEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCiudadEquipoActionPerformed(evt);
            }
        });
        campoCiudadEquipo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                campoCiudadEquipoPropertyChange(evt);
            }
        });

        etiquetaDivisionEquipo.setText("División");

        comboDivisionEquipo.setBackground(new java.awt.Color(255, 255, 255));
        comboDivisionEquipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDivisionEquipoItemStateChanged(evt);
            }
        });

        etiquetaConferenciaEquipo.setText("Conferencia");

        comboConferenciaEquipo.setBackground(new java.awt.Color(255, 255, 255));
        comboConferenciaEquipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboConferenciaEquipoItemStateChanged(evt);
            }
        });
        comboConferenciaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboConferenciaEquipoActionPerformed(evt);
            }
        });

        etiquetaModificarEquipo.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaModificarEquipo.setForeground(new java.awt.Color(218, 26, 50));
        etiquetaModificarEquipo.setText("* Equipo modificado, almacenar los cambios");

        botonModificarEquipo.setBackground(new java.awt.Color(218, 26, 50));
        botonModificarEquipo.setText("Almacenar Cambios");
        botonModificarEquipo.setBorder(null);
        botonModificarEquipo.setBorderPainted(false);
        botonModificarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarEquipoActionPerformed(evt);
            }
        });

        etiquetaNombreEquipo.setText("Nombre");

        campoNombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreEquipoActionPerformed(evt);
            }
        });
        campoNombreEquipo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                campoNombreEquipoPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panelDetallesEquipoLayout = new javax.swing.GroupLayout(panelDetallesEquipo);
        panelDetallesEquipo.setLayout(panelDetallesEquipoLayout);
        panelDetallesEquipoLayout.setHorizontalGroup(
            panelDetallesEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesEquipoLayout.createSequentialGroup()
                .addGroup(panelDetallesEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesEquipoLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(botonModificarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetallesEquipoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelDetallesEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiquetaModificarEquipo)
                            .addComponent(etiquetaCiudadEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCiudadEquipo)
                            .addComponent(etiquetaDivisionEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDivisionEquipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboConferenciaEquipo, 0, 305, Short.MAX_VALUE)
                            .addComponent(etiquetaConferenciaEquipo)
                            .addComponent(etiquetaNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNombreEquipo))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        panelDetallesEquipoLayout.setVerticalGroup(
            panelDetallesEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaNombreEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaCiudadEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCiudadEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(etiquetaDivisionEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboDivisionEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(etiquetaConferenciaEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboConferenciaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaModificarEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonModificarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout panelEquiposLayout = new javax.swing.GroupLayout(panelEquipos);
        panelEquipos.setLayout(panelEquiposLayout);
        panelEquiposLayout.setHorizontalGroup(
            panelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(comboSeleccionConferencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(panelDetallesEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEquiposLayout.setVerticalGroup(
            panelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquiposLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDetallesEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelEquiposLayout.createSequentialGroup()
                        .addComponent(comboSeleccionConferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPestanyas.addTab("tab1", panelEquipos);

        panelJugadores.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Busqueda de Jugadores por Equipo");

        javax.swing.GroupLayout panelJugadoresLayout = new javax.swing.GroupLayout(panelJugadores);
        panelJugadores.setLayout(panelJugadoresLayout);
        panelJugadoresLayout.setHorizontalGroup(
            panelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugadoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(618, Short.MAX_VALUE))
        );
        panelJugadoresLayout.setVerticalGroup(
            panelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugadoresLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        panelPestanyas.addTab("tab2", panelJugadores);

        jLayeredPane1.setLayer(panelPestanyas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(panelPestanyas, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 372, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPestanyas)
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(panelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLateral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEquipoLateralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEquipoLateralMouseEntered
        // TODO add your handling code here:
        //botonEquipoLateral.setBackground(Color.decode("#da1a32"));
        botonEquipoLateral.setBorderPainted(true);
    }//GEN-LAST:event_botonEquipoLateralMouseEntered

    private void botonEquipoLateralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEquipoLateralMouseExited
        // TODO add your handling code here:
        botonEquipoLateral.setBorderPainted(false);
    }//GEN-LAST:event_botonEquipoLateralMouseExited

    private void botonEquipoLateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEquipoLateralActionPerformed
        // TODO add your handling code here:
        botonEquipoLateral.setOpaque(true);
        botonEquipoLateral.setBackground(colorRojo);
        botonJugadoresLateral.setBackground(colorAzul);
        botonEntrenadoresLateral.setBackground(colorAzul);
        botonLesionesLateral.setBackground(colorAzul);
        
        panelPestanyas.setSelectedComponent(panelEquipos);
        etiquetaRutaPanelSuperior.setText("Management\\Equipos");
        etiquetaTituloPanelSuperio.setText("Equipos de la liga");
        
    }//GEN-LAST:event_botonEquipoLateralActionPerformed

    private void botonJugadoresLateralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugadoresLateralMouseEntered
        // TODO add your handling code here:
        botonJugadoresLateral.setBorderPainted(true);
    }//GEN-LAST:event_botonJugadoresLateralMouseEntered

    private void botonJugadoresLateralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugadoresLateralMouseExited
        // TODO add your handling code here:
        botonJugadoresLateral.setBorderPainted(false);
    }//GEN-LAST:event_botonJugadoresLateralMouseExited

    private void botonJugadoresLateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugadoresLateralActionPerformed
        // TODO add your handling code here:
        botonJugadoresLateral.setOpaque(true);
        botonJugadoresLateral.setBackground(colorRojo);
        botonEquipoLateral.setBackground(colorAzul);
        botonEntrenadoresLateral.setBackground(colorAzul);
        botonLesionesLateral.setBackground(colorAzul);
        
        panelPestanyas.setSelectedComponent(panelJugadores);
        
        etiquetaRutaPanelSuperior.setText("Management\\Jugadores");
        etiquetaTituloPanelSuperio.setText("Jugadores por equipos");
        
        
    }//GEN-LAST:event_botonJugadoresLateralActionPerformed

    private void botonEntrenadoresLateralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntrenadoresLateralMouseEntered
        // TODO add your handling code here:
        botonEntrenadoresLateral.setBorderPainted(true);
    }//GEN-LAST:event_botonEntrenadoresLateralMouseEntered

    private void botonEntrenadoresLateralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntrenadoresLateralMouseExited
        // TODO add your handling code here:
        botonEntrenadoresLateral.setBorderPainted(false);
    }//GEN-LAST:event_botonEntrenadoresLateralMouseExited

    private void botonEntrenadoresLateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrenadoresLateralActionPerformed
        // TODO add your handling code here:
        botonEntrenadoresLateral.setOpaque(true);
        botonJugadoresLateral.setBackground(colorAzul);
        botonEquipoLateral.setBackground(colorAzul);
        botonEntrenadoresLateral.setBackground(colorRojo);
        botonLesionesLateral.setBackground(colorAzul);
    }//GEN-LAST:event_botonEntrenadoresLateralActionPerformed

    private void botonLesionesLateralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLesionesLateralMouseEntered
        // TODO add your handling code here:
        botonLesionesLateral.setBorderPainted(true);
    }//GEN-LAST:event_botonLesionesLateralMouseEntered

    private void botonLesionesLateralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLesionesLateralMouseExited
        // TODO add your handling code here:
        botonLesionesLateral.setBorderPainted(false);
    }//GEN-LAST:event_botonLesionesLateralMouseExited

    private void botonLesionesLateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLesionesLateralActionPerformed
        // TODO add your handling code here:
        botonLesionesLateral.setOpaque(true);
        botonJugadoresLateral.setBackground(colorAzul);
        botonEquipoLateral.setBackground(colorAzul);
        botonEntrenadoresLateral.setBackground(colorAzul);
        botonLesionesLateral.setBackground(colorRojo);
    }//GEN-LAST:event_botonLesionesLateralActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        //Desactivar las opciones de actualización
        
        botonModificarEquipo.setVisible(false);
        etiquetaModificarEquipo.setVisible(false);
        
        //Cargamos las conferencias almacenadas en la BD dentro del comboBox de conferencias
        
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloConferenciasEquipo = new DefaultComboBoxModel();
        modeloCombo.addAll(modelo.getConferencias());
        modeloConferenciasEquipo.addAll(modelo.getConferencias());
        comboSeleccionConferencia.setModel(modeloCombo);
        
        comboSeleccionConferencia.setSelectedIndex(1);
        
        
        
        DefaultListModel modeloLista = new DefaultListModel();
        for (Equipo e: modelo.getEquiposConferencia(comboSeleccionConferencia.getSelectedItem().toString())){
            modeloLista.addElement(e.getNombre());
        }
        
        listaConferenciaEquipos.setModel(modeloLista);
        
        
        //Cargamos los datos de las conferencias y divisiones
        
        comboConferenciaEquipo.setModel(modeloConferenciasEquipo);
    }//GEN-LAST:event_formComponentShown

    private void comboSeleccionConferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionConferenciaActionPerformed
        // TODO add your handling code here:
        DefaultListModel modeloLista = new DefaultListModel();
        for (Equipo e: modelo.getEquiposConferencia(comboSeleccionConferencia.getSelectedItem().toString())){
            modeloLista.addElement(e.getNombre());
        }
        
        listaConferenciaEquipos.setModel(modeloLista);
    }//GEN-LAST:event_comboSeleccionConferenciaActionPerformed

    private void listaConferenciaEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaConferenciaEquiposMouseClicked
        // TODO add your handling code here:
        cargarDatosEquipo(listaConferenciaEquipos.getSelectedValue());
    }//GEN-LAST:event_listaConferenciaEquiposMouseClicked

    private void comboConferenciaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConferenciaEquipoActionPerformed
        // TODO add your handling code here:
        if(comboConferenciaEquipo.getSelectedItem().equals("Oeste")){
            DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
            modeloCombo.addAll(modelo.getDivisionesOeste());
            comboDivisionEquipo.setModel(modeloCombo);
        }else{
            DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
            modeloCombo.addAll(modelo.getDivisionesEste());
            comboDivisionEquipo.setModel(modeloCombo);
        }
    }//GEN-LAST:event_comboConferenciaEquipoActionPerformed

    private void campoCiudadEquipoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_campoCiudadEquipoPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoCiudadEquipoPropertyChange

    private void comboDivisionEquipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDivisionEquipoItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboDivisionEquipoItemStateChanged

    private void comboConferenciaEquipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboConferenciaEquipoItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboConferenciaEquipoItemStateChanged

    private void campoCiudadEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCiudadEquipoActionPerformed
        // TODO add your handling code here:
//        
    }//GEN-LAST:event_campoCiudadEquipoActionPerformed

    private void botonModificarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarEquipoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonModificarEquipoActionPerformed

    private void campoNombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreEquipoActionPerformed

    private void campoNombreEquipoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_campoNombreEquipoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreEquipoPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaControlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaControlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaControlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaControlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaControlador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEntrenadoresLateral;
    private javax.swing.JButton botonEquipoLateral;
    private javax.swing.JButton botonJugadoresLateral;
    private javax.swing.JButton botonLesionesLateral;
    private javax.swing.JButton botonModificarEquipo;
    private javax.swing.JTextField campoCiudadEquipo;
    private javax.swing.JTextField campoNombreEquipo;
    private javax.swing.JComboBox<String> comboConferenciaEquipo;
    private javax.swing.JComboBox<String> comboDivisionEquipo;
    private javax.swing.JComboBox<String> comboSeleccionConferencia;
    private javax.swing.JLabel etiquetaCiudadEquipo;
    private javax.swing.JLabel etiquetaConferenciaEquipo;
    private javax.swing.JLabel etiquetaDivisionEquipo;
    private javax.swing.JLabel etiquetaLogotipo;
    private javax.swing.JLabel etiquetaModificarEquipo;
    private javax.swing.JLabel etiquetaNombreEquipo;
    private javax.swing.JLabel etiquetaRutaPanelSuperior;
    private javax.swing.JLabel etiquetaTituloPanelSuperio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> listaConferenciaEquipos;
    private javax.swing.JPanel panelDetallesEquipo;
    private javax.swing.JPanel panelEquipos;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelJugadores;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JTabbedPane panelPestanyas;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
    private static final Color colorRojo = Color.decode("#da1a32");
    private static final Color colorAzul = Color.decode("#00438c");
    private boolean mostrarEncabezado = false;
    
    private DAOImplementacionHibernate modelo = new DAOImplementacionHibernate();
    
    private Equipo equipoSeleccionadoActual;
    private boolean insercion = false;

    //Funciones auxiliares
    
    private void cargarDatosEquipo(String nombreEquipo){
        
        
        
        Equipo e= modelo.getEquipoPorNombre(nombreEquipo);
        equipoSeleccionadoActual=e;
        TitledBorder bordepanel = new TitledBorder("Datos "+e.getCiudad()+" "+e.getNombre());
        panelDetallesEquipo.setBorder(bordepanel);
        
        campoCiudadEquipo.setText(e.getNombre());
        comboConferenciaEquipo.setSelectedItem(e.getConferencia());
        
        if(e.getConferencia().equals("Oeste")){
            DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
            modeloCombo.addAll(modelo.getDivisionesOeste());
            comboDivisionEquipo.setModel(modeloCombo);
        }else{
            DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
            modeloCombo.addAll(modelo.getDivisionesEste());
            comboDivisionEquipo.setModel(modeloCombo);
        }
        
        comboDivisionEquipo.setSelectedItem(e.getDivision());
        
    }
    
    private Equipo crearDatosEquipoConCampos(){
        if(insercion){
            return new Equipo(modelo.getIdInsertarEquipo(),campoNombreEquipo.getText(),campoCiudadEquipo.getText(),(String)comboDivisionEquipo.getSelectedItem(),(String)comboConferenciaEquipo.getSelectedItem(),equipoSeleccionadoActual.getEntrenador(),equipoSeleccionadoActual.getJugadores());
        }else{
            return new Equipo(equipoSeleccionadoActual.getId(),campoNombreEquipo.getText(),campoCiudadEquipo.getText(),(String)comboDivisionEquipo.getSelectedItem(),(String)comboConferenciaEquipo.getSelectedItem(),equipoSeleccionadoActual.getEntrenador(),equipoSeleccionadoActual.getJugadores());
        }
        
    }
}
