/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.iespacomolla.ad.accesodatos;

import es.iespacomolla.ad.exceptions.DAOEquipoExcepcion;
import es.iespacomolla.ad.hibernateaccesodatos.Entrenador;
import es.iespacomolla.ad.hibernateaccesodatos.Equipo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author miguel
 */
public class InsercionEquipos extends javax.swing.JFrame {

    /**
     * Creates new form InsercionEquipos
     */
    public InsercionEquipos() {
        initComponents();
        
        campoNombreInsercionEquipo.setText("");
        campoCiudadInsercionEquipo.setText("");
        DefaultComboBoxModel modeloConferencias = new DefaultComboBoxModel();
        modeloConferencias.addAll(modelo.getConferencias());
        comboConferenciasInsercionEquipos.setModel(modeloConferencias);
        comboConferenciasInsercionEquipos.setSelectedIndex(-1);
        comboDivisionInsercionEquipos.setSelectedIndex(-1);
        DefaultListModel modeloEntrenadores = new DefaultListModel();
        for(Entrenador e : modelo.getEntrenadoresSinEquipo()){
            modeloEntrenadores.addElement(e.getNombre());
        }
        jList1.setModel(modeloEntrenadores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperiorInsercionEquipo = new javax.swing.JPanel();
        etiquetaInsercionEquipos = new javax.swing.JLabel();
        etiquetaRutaPanelSuperior = new javax.swing.JLabel();
        panelDatosNuevoEquipo = new javax.swing.JPanel();
        etiquetaNombreInsercionEquipo = new javax.swing.JLabel();
        campoNombreInsercionEquipo = new javax.swing.JTextField();
        campoCiudadInsercionEquipo = new javax.swing.JTextField();
        etiquetaCiudadInsercionEquipo = new javax.swing.JLabel();
        etiquetaConferenciaInsercionEquipo = new javax.swing.JLabel();
        comboConferenciasInsercionEquipos = new javax.swing.JComboBox<>();
        comboDivisionInsercionEquipos = new javax.swing.JComboBox<>();
        etiquetaDivisionInsercionEquipos = new javax.swing.JLabel();
        botonInsertarEquipo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelSuperiorInsercionEquipo.setBackground(new java.awt.Color(218, 26, 50));

        etiquetaInsercionEquipos.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        etiquetaInsercionEquipos.setText("Insertar un nuevo equipo");

        etiquetaRutaPanelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaRutaPanelSuperior.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        etiquetaRutaPanelSuperior.setText("Management\\Equipos");

        javax.swing.GroupLayout panelSuperiorInsercionEquipoLayout = new javax.swing.GroupLayout(panelSuperiorInsercionEquipo);
        panelSuperiorInsercionEquipo.setLayout(panelSuperiorInsercionEquipoLayout);
        panelSuperiorInsercionEquipoLayout.setHorizontalGroup(
            panelSuperiorInsercionEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorInsercionEquipoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelSuperiorInsercionEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaRutaPanelSuperior)
                    .addComponent(etiquetaInsercionEquipos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSuperiorInsercionEquipoLayout.setVerticalGroup(
            panelSuperiorInsercionEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorInsercionEquipoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(etiquetaRutaPanelSuperior)
                .addGap(18, 18, 18)
                .addComponent(etiquetaInsercionEquipos)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelDatosNuevoEquipo.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosNuevoEquipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del nuevo equipo"));

        etiquetaNombreInsercionEquipo.setText("Introduzca el nombre del equipo:");

        campoNombreInsercionEquipo.setNextFocusableComponent(campoCiudadInsercionEquipo);

        etiquetaCiudadInsercionEquipo.setText("Introduzca la ciudad del equipo:");

        etiquetaConferenciaInsercionEquipo.setText("Introduzca la conferencia del equipo:");

        comboConferenciasInsercionEquipos.setBackground(new java.awt.Color(255, 255, 255));
        comboConferenciasInsercionEquipos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboConferenciasInsercionEquiposItemStateChanged(evt);
            }
        });

        comboDivisionInsercionEquipos.setBackground(new java.awt.Color(255, 255, 255));

        etiquetaDivisionInsercionEquipos.setText("Introduzca la división del equipo:");

        botonInsertarEquipo.setBackground(new java.awt.Color(218, 26, 50));
        botonInsertarEquipo.setText("Guardar Nuevo Equipo");
        botonInsertarEquipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 26, 50)));
        botonInsertarEquipo.setBorderPainted(false);
        botonInsertarEquipo.setOpaque(true);
        botonInsertarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarEquipoActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout panelDatosNuevoEquipoLayout = new javax.swing.GroupLayout(panelDatosNuevoEquipo);
        panelDatosNuevoEquipo.setLayout(panelDatosNuevoEquipoLayout);
        panelDatosNuevoEquipoLayout.setHorizontalGroup(
            panelDatosNuevoEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosNuevoEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosNuevoEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaCiudadInsercionEquipo)
                    .addGroup(panelDatosNuevoEquipoLayout.createSequentialGroup()
                        .addComponent(etiquetaDivisionInsercionEquipos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboDivisionInsercionEquipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosNuevoEquipoLayout.createSequentialGroup()
                        .addComponent(etiquetaConferenciaInsercionEquipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboConferenciasInsercionEquipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDatosNuevoEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(campoCiudadInsercionEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosNuevoEquipoLayout.createSequentialGroup()
                            .addComponent(etiquetaNombreInsercionEquipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoNombreInsercionEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosNuevoEquipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonInsertarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        panelDatosNuevoEquipoLayout.setVerticalGroup(
            panelDatosNuevoEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosNuevoEquipoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelDatosNuevoEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosNuevoEquipoLayout.createSequentialGroup()
                        .addGroup(panelDatosNuevoEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaNombreInsercionEquipo)
                            .addComponent(campoNombreInsercionEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelDatosNuevoEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaCiudadInsercionEquipo)
                            .addComponent(campoCiudadInsercionEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(panelDatosNuevoEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaConferenciaInsercionEquipo)
                            .addComponent(comboConferenciasInsercionEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(panelDatosNuevoEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaDivisionInsercionEquipos)
                            .addComponent(comboDivisionInsercionEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(botonInsertarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorInsercionEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDatosNuevoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSuperiorInsercionEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(panelDatosNuevoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInsertarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarEquipoActionPerformed
        // TODO add your handling code here:
        Equipo e = new Equipo(modelo.getIdInsertarEquipo(), campoNombreInsercionEquipo.getText(), campoCiudadInsercionEquipo.getText(), comboDivisionInsercionEquipos.getSelectedItem().toString(), comboConferenciasInsercionEquipos.getSelectedItem().toString(), modelo.getEntrenadorPorNombre(jList1.getSelectedValue()), null);
        try {
            modelo.setEquipo(e);
        } catch (DAOEquipoExcepcion ex) {
            JOptionPane.showMessageDialog(this, "Error: No se ha podido almacenar el equipo\n"+ex.getMessage());
        }

        

    }//GEN-LAST:event_botonInsertarEquipoActionPerformed

    private void comboConferenciasInsercionEquiposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboConferenciasInsercionEquiposItemStateChanged
        // TODO add your handling code here:
        DefaultComboBoxModel modeloCombo = null;
        if(comboConferenciasInsercionEquipos.getSelectedItem().equals("Oeste")){
            modeloCombo = new DefaultComboBoxModel();
            modeloCombo.addAll(modelo.getDivisionesOeste());
            comboDivisionInsercionEquipos.setModel(modeloCombo);
        }else{
            modeloCombo = new DefaultComboBoxModel();
            modeloCombo.addAll(modelo.getDivisionesEste());
            comboDivisionInsercionEquipos.setModel(modeloCombo);
        }
    }//GEN-LAST:event_comboConferenciasInsercionEquiposItemStateChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInsertarEquipo;
    private javax.swing.JTextField campoCiudadInsercionEquipo;
    private javax.swing.JTextField campoNombreInsercionEquipo;
    private javax.swing.JComboBox<String> comboConferenciasInsercionEquipos;
    private javax.swing.JComboBox<String> comboDivisionInsercionEquipos;
    private javax.swing.JLabel etiquetaCiudadInsercionEquipo;
    private javax.swing.JLabel etiquetaConferenciaInsercionEquipo;
    private javax.swing.JLabel etiquetaDivisionInsercionEquipos;
    private javax.swing.JLabel etiquetaInsercionEquipos;
    private javax.swing.JLabel etiquetaNombreInsercionEquipo;
    private javax.swing.JLabel etiquetaRutaPanelSuperior;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatosNuevoEquipo;
    private javax.swing.JPanel panelSuperiorInsercionEquipo;
    // End of variables declaration//GEN-END:variables

    private DAOImplementacionHibernate modelo = new DAOImplementacionHibernate();
}
